services:
  es8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    environment:
      - cluster.name=docker-test-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - cluster.routing.allocation.disk.threshold_enabled=true
      # make sure it works on nearly full disk
      - cluster.routing.allocation.disk.watermark.low=3gb
      - cluster.routing.allocation.disk.watermark.high=2gb
      - cluster.routing.allocation.disk.watermark.flood_stage=1gb
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
      - network.host=127.0.0.1
      - http.host=0.0.0.0

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      # give our test instance a port number that is for sure not going to write to some poor cluster listening on 9200
      - "9999:9200"
