project:
  type: book
  output-dir: quarto
book:
  title: "KT Search Manual"
  chapters:
    - index.md
    - WhatIsKtSearch.md
    - GettingStarted.md
    - ClientConfiguration.md
    - IndexManagement.md
    - Search.md
    - TextQueries.md
    - TermLevelQueries.md
    - CompoundQueries.md
    - GeoQueries.md
    - SpecializedQueries.md
    - Aggregations.md
    - DeepPaging.md
    - JoinQueries.md
    - Highlighting.md
    - ReusableSearchQueries.md
    - DeleteByQuery.md
    - DocumentManipulation.md
    - IndexRepository.md
    - BulkIndexing.md
    - DataStreams.md
    - KnnSearch.md
    - ExtendingTheDSL.md
    - Scripting.md
    - Jupyter.md
    - Migrating.md
format:
  html:
    theme: cosmo
  pdf: default
  epub: default
