package com.jillesvangurp.ktsearch.cli

import com.github.ajalt.clikt.command.parse
import com.github.ajalt.clikt.core.ProgramResult
import com.github.ajalt.clikt.core.PrintHelpMessage
import com.jillesvangurp.ktsearch.cli.command.root.KtSearchCommand
import io.kotest.matchers.shouldBe
import java.io.ByteArrayOutputStream
import java.io.PrintStream
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import kotlin.test.Test
import kotlinx.coroutines.test.runTest

class CliManualTest {
    @Test
    fun generateCliManualMarkdown() = runTest {
        val sections = commandPaths.map { path ->
            val command = if (path.isEmpty()) {
                "ktsearch"
            } else {
                "ktsearch ${path.joinToString(" ")}"
            }
            HelpSection(
                command = command,
                output = captureHelp(path),
            )
        }

        val markdown = buildString {
            appendLine("# CLI manual")
            appendLine()
            appendLine("Generated by `CliManualTest.generateCliManualMarkdown`.")
            appendLine()
            sections.forEach { section ->
                appendLine("## `${section.command}`")
                appendLine()
                appendLine("```text")
                appendLine(section.output)
                appendLine("```")
                appendLine()
            }
        }

        val outputFile = outputFile()
        Files.writeString(outputFile, markdown)

        Files.exists(outputFile) shouldBe true
    }

    private suspend fun captureHelp(path: List<String>): String {
        val args = (path + "--help").toTypedArray()
        val out = ByteArrayOutputStream()
        val err = ByteArrayOutputStream()
        val previousOut = System.out
        val previousErr = System.err
        var fallbackHelp: String? = null

        try {
            System.setOut(PrintStream(out, true, "UTF-8"))
            System.setErr(PrintStream(err, true, "UTF-8"))

            val command = KtSearchCommand()
            val failure = runCatching { command.parse(args) }.exceptionOrNull()
            if (failure != null) {
                when (failure) {
                    is PrintHelpMessage -> {
                        fallbackHelp = command.getFormattedHelp(failure)
                    }
                    is ProgramResult -> {
                        if (failure.statusCode != 0) {
                            throw failure
                        }
                    }
                    else -> throw failure
                }
            }
        } finally {
            System.setOut(previousOut)
            System.setErr(previousErr)
        }

        val stdout = out.toString("UTF-8").trim()
        val stderr = err.toString("UTF-8").trim()
        return when {
            stdout.isNotBlank() -> stdout.trimEnd()
            stderr.isNotBlank() -> stderr.trimEnd()
            !fallbackHelp.isNullOrBlank() -> fallbackHelp!!.trimEnd()
            else -> ""
        }
    }

    private fun outputFile(): Path {
        return findProjectRoot().resolve("ktsearch-cli").resolve("cli-manual.md")
    }

    private fun findProjectRoot(): Path {
        var current: Path? = Paths.get("").toAbsolutePath()
        while (current != null) {
            if (Files.exists(current.resolve("settings.gradle.kts"))) {
                return current
            }
            current = current.parent
        }
        error("Unable to locate project root from ${Paths.get("").toAbsolutePath()}")
    }

    private companion object {
        val commandPaths = listOf(
            emptyList(),
            listOf("cluster"),
            listOf("cluster", "health"),
            listOf("cluster", "stats"),
            listOf("cluster", "state"),
            listOf("cluster", "settings"),
            listOf("cluster", "pending-tasks"),
            listOf("info"),
            listOf("cat"),
            listOf("cat", "aliases"),
            listOf("cat", "allocation"),
            listOf("cat", "count"),
            listOf("cat", "health"),
            listOf("cat", "indices"),
            listOf("cat", "master"),
            listOf("cat", "nodes"),
            listOf("cat", "pending-tasks"),
            listOf("cat", "recovery"),
            listOf("cat", "repositories"),
            listOf("cat", "shards"),
            listOf("cat", "snapshots"),
            listOf("cat", "tasks"),
            listOf("cat", "templates"),
            listOf("cat", "thread-pool"),
            listOf("index"),
            listOf("index", "create"),
            listOf("index", "put"),
            listOf("index", "get"),
            listOf("index", "show"),
            listOf("index", "exists"),
            listOf("index", "delete"),
            listOf("index", "rm"),
            listOf("index", "doc"),
            listOf("index", "doc", "get"),
            listOf("index", "doc", "index"),
            listOf("index", "doc", "delete"),
            listOf("index", "doc", "mget"),
            listOf("index", "mappings"),
            listOf("index", "mappings", "get"),
            listOf("index", "mappings", "put"),
            listOf("index", "settings"),
            listOf("index", "settings", "get"),
            listOf("index", "settings", "put"),
            listOf("index", "template"),
            listOf("index", "template", "component"),
            listOf("index", "template", "component", "get"),
            listOf("index", "template", "component", "put"),
            listOf("index", "template", "component", "delete"),
            listOf("index", "template", "index"),
            listOf("index", "template", "index", "get"),
            listOf("index", "template", "index", "put"),
            listOf("index", "template", "index", "delete"),
            listOf("index", "data-stream"),
            listOf("index", "data-stream", "create"),
            listOf("index", "data-stream", "get"),
            listOf("index", "data-stream", "delete"),
            listOf("index", "alias"),
            listOf("index", "alias", "get"),
            listOf("index", "alias", "update"),
            listOf("index", "alias", "add"),
            listOf("index", "alias", "remove"),
            listOf("index", "alias", "remove-index"),
            listOf("index", "snapshot"),
            listOf("index", "snapshot", "repo"),
            listOf("index", "snapshot", "repo", "create"),
            listOf("index", "snapshot", "repo", "get"),
            listOf("index", "snapshot", "repo", "delete"),
            listOf("index", "snapshot", "repo", "verify"),
            listOf("index", "snapshot", "create"),
            listOf("index", "snapshot", "list"),
            listOf("index", "snapshot", "delete"),
            listOf("index", "snapshot", "restore"),
            listOf("index", "reindex"),
            listOf("index", "reindex-task-status"),
            listOf("index", "reindex-wait"),
            listOf("index", "ilm"),
            listOf("index", "ilm", "put"),
            listOf("index", "ilm", "get"),
            listOf("index", "ilm", "delete"),
            listOf("index", "ilm", "status"),
            listOf("index", "apply"),
            listOf("index", "wait-green"),
            listOf("index", "wait-exists"),
            listOf("index", "dump"),
            listOf("index", "restore"),
            listOf("index", "search"),
            listOf("completion"),
        )
    }
}

private data class HelpSection(
    val command: String,
    val output: String,
)
